board: silinux: ek874: fix compile warning for i2c funcs
Below warnings are occured when do compiling:
| board/silinux/ek874/ek874.c: In function 'board_late_init':
| board/silinux/ek874/ek874.c:111:8: warning: implicit declaration of function 'i2c_get_chip_for_busnum' [-Wimplicit-function-declaration]
|   ret = i2c_get_chip_for_busnum(clock_gen_i2c_bus, clock_gen_addr, 1,
|         ^~~~~~~~~~~~~~~~~~~~~~~
| board/silinux/ek874/ek874.c:114:3: warning: implicit declaration of function 'dm_i2c_write'; did you mean 'isa_writew'? [-Wimplicit-function-declaration]
|    dm_i2c_write(dev, 0x81, 0x4, 1);

Fix these issues by adding missing header and defining a variable for
I2C buffer value.

Signed-off-by: hienhuynh <hien.huynh.px@renesas.com>